'use client';

import { motion } from 'framer-motion';
import { Sparkles, Brain, TrendingUp, AlertCircle } from 'lucide-react';

interface AIInsightsProps {
  insights: {
    summary: string;
    generated_by: string;
    confidence: string;
  };
  recommendation?: string;
  behaviorPatterns?: string;
}

export default function AIInsights({ insights, recommendation, behaviorPatterns }: AIInsightsProps) {
  const getConfidenceColor = (confidence: string) => {
    switch (confidence) {
      case 'high':
        return 'text-green-600 bg-green-50 border-green-200';
      case 'medium':
        return 'text-yellow-600 bg-yellow-50 border-yellow-200';
      case 'low':
        return 'text-red-600 bg-red-50 border-red-200';
      default:
        return 'text-gray-600 bg-gray-50 border-gray-200';
    }
  };

  return (
    <div className="space-y-6">
      {/* AI Summary */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 rounded-2xl p-8 border-2 border-purple-200 dark:border-purple-800"
      >
        <div className="flex items-center space-x-3 mb-6">
          <div className="p-3 bg-purple-600 rounded-full">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="text-2xl font-bold text-gray-900 dark:text-white">
              AI-Powered Insights
            </h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Generated by {insights.generated_by}
            </p>
          </div>
          <div className="ml-auto">
            <span className={`px-3 py-1 rounded-full text-xs font-semibold ${getConfidenceColor(insights.confidence)} border`}>
              {insights.confidence.toUpperCase()} CONFIDENCE
            </span>
          </div>
        </div>

        <div className="prose dark:prose-invert max-w-none">
          <p className="text-lg text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">
            {insights.summary}
          </p>
        </div>

        {/* Sparkle animation */}
        <motion.div
          animate={{
            scale: [1, 1.2, 1],
            rotate: [0, 180, 360],
          }}
          transition={{
            duration: 3,
            repeat: Infinity,
            ease: "easeInOut"
          }}
          className="absolute top-4 right-4 opacity-20"
        >
          <Sparkles className="w-8 h-8 text-purple-600" />
        </motion.div>
      </motion.div>

      {/* Recommendation */}
      {recommendation && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white dark:bg-gray-800 rounded-xl p-6 border-2 border-gray-200 dark:border-gray-700"
        >
          <div className="flex items-start space-x-3">
            <TrendingUp className="w-6 h-6 text-blue-600 mt-1" />
            <div>
              <h4 className="font-bold text-lg mb-2 text-gray-900 dark:text-white">
                Hiring Recommendation
              </h4>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                {recommendation}
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Behavior Patterns */}
      {behaviorPatterns && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="bg-white dark:bg-gray-800 rounded-xl p-6 border-2 border-gray-200 dark:border-gray-700"
        >
          <div className="flex items-start space-x-3">
            <AlertCircle className="w-6 h-6 text-orange-600 mt-1" />
            <div>
              <h4 className="font-bold text-lg mb-2 text-gray-900 dark:text-white">
                Behavior Analysis
              </h4>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                {behaviorPatterns}
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Disclaimer */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="text-xs text-center text-gray-500 dark:text-gray-400 italic"
      >
        AI-generated insights are meant to assist decision-making, not replace human judgment.
        Always verify findings through interviews and code reviews.
      </motion.div>
    </div>
  );
}